import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { NextUIProvider } from "@nextui-org/react";
import Header from "@/components/header/Header";
import { ThemeProvider as NextThemesProvider } from "next-themes";

const Yekan = localFont({
  src: [
    {
      path: "./fonts/YekanBakhRegular.woff2",
      weight: "500",
      style: "Normal",
    },
    {
      path: "./fonts/YekanBakhSemiBold.woff2",
      weight: "600",
      style: "SemiBold",
    },
    {
      path: "./fonts/YekanBakhBold.woff2",
      weight: "700",
      style: "Bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${Yekan.className}`}>
        <NextUIProvider>
          <NextThemesProvider attribute="class" defaultTheme="light">
            <Header />
            {children}
          </NextThemesProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
